# -*- coding: utf-8 -*-

# @Time : 2022/4/11 20:49
# @Author : 石张毅
# @Site : 
# @File : index.py
# @Software: PyCharm 

def index():
    cates = [
     # {'provincial_capital': '澳门', 'url': 'aomen', 'page': 2},
     #安徽省
     # {'provincial_capital': '合肥', 'url': 'hefei', 'page': 74},#74
     # {'provincial_capital': '蚌埠', 'url': 'bangbu', 'page': 25},
     # {'provincial_capital': '芜湖', 'url': 'wuhu', 'page': 38},
     # {'provincial_capital': '马鞍山', 'url': 'maanshan', 'page': 24},
     # {'provincial_capital': '安庆', 'url': 'anqing', 'page': 51},
     # {'provincial_capital': '黄山', 'url': 'huangshan', 'page': 38},
     # {'provincial_capital': '巢湖', 'url': 'chaohu', 'page': 1},
     # {'provincial_capital': '亳州', 'url': 'haozhou', 'page': 40},
     # #{'provincial_capital': '六安', 'url': 'liuan', 'page': 48},
     # {'provincial_capital': '宣城', 'url': 'xuancheng', 'page': 30},
     # {'provincial_capital': '宿州', 'url': 'suuzhou', 'page': 41},
     # #{'provincial_capital': '池州', 'url': 'chizhou', 'page': 29},
     # {'provincial_capital': '淮北', 'url': 'huaibei', 'page': 17},
     # {'provincial_capital': '淮南', 'url': 'huainan', 'page': 20},
     # {'provincial_capital': '滁州', 'url': 'chuzhou', 'page': 42},
     # {'provincial_capital': '铜陵', 'url': 'tongling', 'page': 14},
     # {'provincial_capital': '阜阳', 'url': 'fuyang', 'page': 40},
     # # 福建省
     # {'provincial_capital': '福州', 'url': 'fuzhou', 'page': 47},
     # {'provincial_capital': '厦门', 'url': 'xiamen', 'page': 25},
     # {'provincial_capital': '宁德', 'url': 'ningde', 'page': 30},
     # {'provincial_capital': '莆田', 'url': 'putian', 'page': 20},
     # {'provincial_capital': '泉州', 'url': 'quanzhou', 'page': 39},
     # {'provincial_capital': '漳州', 'url': 'zhangzhou', 'page': 27},
    ## {'provincial_capital': '三明', 'url': 'sanming', 'page': 29},
    #  {'provincial_capital': '南平', 'url': 'nanping', 'page': 27},
    #  {'provincial_capital': '龙岩', 'url': 'longyan', 'page': 24},
     # # 广东省
     # {'provincial_capital': '深圳', 'url': 'shenzhen', 'page': 26},
     # {'provincial_capital': '珠海', 'url': 'zhuhai', 'page': 15},
     ##{'provincial_capital': '佛山', 'url': 'foshan', 'page': 37},
      ##{'provincial_capital': '肇庆', 'url': 'zhaoqing', 'page': 39},
     # {'provincial_capital': '汕头', 'url': 'shantou', 'page': 19},
     # {'provincial_capital': '湛江', 'url': 'zhanjiang', 'page': 26},
     # {'provincial_capital': '中山', 'url': 'zhongshan', 'page': 19},
     # {'provincial_capital': '潮州', 'url': 'chaozhou', 'page': 20},
     # {'provincial_capital': '东莞', 'url': 'dongguan', 'page': 23},
    ## {'provincial_capital': '阳江', 'url': 'yangjiang', 'page': 25},
     # {'provincial_capital': '揭阳', 'url': 'jieyang', 'page': 19},
     # {'provincial_capital': '茂名', 'url': 'maoming', 'page': 39},
     # {'provincial_capital': '江门', 'url': 'jiangmen', 'page': 39},
     ##{'provincial_capital': '韶关', 'url': 'shaoguan', 'page': 38},
     ##{'provincial_capital': '惠州', 'url': 'huizhou', 'page': 46},
     ## {'provincial_capital': '梅州', 'url': 'meizhou', 'page': 57},
     ## {'provincial_capital': '云浮', 'url': 'yunfu', 'page': 33} ,
     # {'provincial_capital': '河源', 'url': 'heyuan', 'page': 40},
     # {'provincial_capital': '清远', 'url': 'qingyuan', 'page': 67},
     # # 广西省
     # {'provincial_capital': '南宁', 'url': 'nanning', 'page': 40},
     # {'provincial_capital': '柳州', 'url': 'liuzhou', 'page': 32},
     ##{'provincial_capital': '桂林', 'url': 'guilin', 'page': 61},
     # {'provincial_capital': '北海', 'url': 'beihai', 'page': 14},
     # {'provincial_capital': '防城港', 'url': 'fangchenggang', 'page': 18},
     # {'provincial_capital': '崇左', 'url': 'chongzuo', 'page': 22},
     # {'provincial_capital': '来宾', 'url': 'laibin', 'page': 18},
     # {'provincial_capital': '梧州', 'url': 'wuzhou', 'page': 24},
     # {'provincial_capital': '河池', 'url': 'hechi', 'page': 58},
     # {'provincial_capital': '玉林', 'url': 'yulin', 'page': 35},
     # {'provincial_capital': '贵港', 'url': 'guigang', 'page': 36},
     ##{'provincial_capital': '贺州', 'url': 'hezhou', 'page': 33},
      # {'provincial_capital': '钦州', 'url': 'qinzhou', 'page': 32},
     # {'provincial_capital': '百色', 'url': 'baise', 'page': 27},
     # # 贵州省
     ## {'provincial_capital': '贵阳', 'url': 'guiyang', 'page': 39},
    # {'provincial_capital': '安顺', 'url': 'anshun', 'page': 34},
     ##{'provincial_capital': '毕节地区', 'url': 'bijie', 'page': 29},
     ## {'provincial_capital': '遵义', 'url': 'zunyi', 'page': 89},
     # {'provincial_capital': '铜仁地区', 'url': 'tongren', 'page': 23},
    ## {'provincial_capital': '黔东南', 'url': 'qiandongnan', 'page': 40},
      ##{'provincial_capital': '黔南', 'url': 'qiannan', 'page': 36},
      #{'provincial_capital': '六盘水', 'url': 'liupanshui', 'page': 26},
     ## {'provincial_capital': '黔西南州', 'url': 'qianxinanzhou', 'page': 29},
     # # 甘肃省
     ##  {'provincial_capital': '兰州', 'url': 'lanzhou', 'page': 47},
     ## {'provincial_capital': '天水', 'url': 'tianshui', 'page': 37},
     ## {'provincial_capital': '定西', 'url': 'dingxi', 'page': 45},
     ## {'provincial_capital': '平凉', 'url': 'pingliang', 'page': 27},
     # #{'provincial_capital': '庆阳', 'url': 'qingyang', 'page': 48},
     # #{'provincial_capital': '张掖', 'url': 'zhangye', 'page': 27},
     # #{'provincial_capital': '武威', 'url': 'wuwei', 'page': 30},
     ## {'provincial_capital': '白银', 'url': 'baiyin', 'page': 27},
     #{'provincial_capital': '酒泉', 'url': 'jiuquan', 'page': 16},
      # {'provincial_capital': '金昌', 'url': 'jinchang', 'page': 11},
     # #{'provincial_capital': '陇南', 'url': 'longnan', 'page': 38},
     #  {'provincial_capital': '临夏', 'url': 'linxia', 'page': 26},
     # {'provincial_capital': '甘南州', 'url': 'gannanzhou', 'page': 19},
     # {'provincial_capital': '嘉峪关', 'url': 'jiayuguan', 'page': 4},
     # # 河北省
     ## {'provincial_capital': '邯郸', 'url': 'handan', 'page': 43},
     ## {'provincial_capital': '石家庄', 'url': 'shijiazhuang', 'page': 39},
     ## {'provincial_capital': '保定', 'url': 'baoding', 'page': 59},
     ## {'provincial_capital': '张家口', 'url': 'zhangjiakou', 'page': 31},
     ## {'provincial_capital': '承德', 'url': 'chengde', 'page': 59},
     ## {'provincial_capital': '唐山', 'url': 'tangshan', 'page': 34},
    ## {'provincial_capital': '廊坊', 'url': 'langfang', 'page': 20},
     # {'provincial_capital': '秦皇岛', 'url': 'qinhuangdao', 'page': 21},
     ##{'provincial_capital': '沧州', 'url': 'cangzhou', 'page': 30},
     ## {'provincial_capital': '衡水', 'url': 'hengshui', 'page': 40},
     # # 河南省
     # {'provincial_capital': '邢台', 'url': 'xingtai', 'page': 35},
     # {'provincial_capital': '郑州', 'url': 'zhengzhou', 'page': 37},
     # {'provincial_capital': '安阳', 'url': 'anyang', 'page': 26},
     ## {'provincial_capital': '新乡', 'url': 'xinxiang', 'page': 25},
     # {'provincial_capital': '许昌', 'url': 'xuchang', 'page': 23},
     # {'provincial_capital': '平顶山', 'url': 'pingdingshan', 'page': 26},
     ## {'provincial_capital': '开封', 'url': 'kaifeng', 'page': 36},
     ##{'provincial_capital': '洛阳', 'url': 'luoyang', 'page': 51},
     # {'provincial_capital': '焦作', 'url': 'jiaozuo', 'page': 21},
    ## {'provincial_capital': '三门峡', 'url': 'sanmenxia', 'page': 29},
     ##{'provincial_capital': '信阳', 'url': 'xinyang', 'page': 45},
     ## {'provincial_capital': '南阳', 'url': 'nanyang', 'page': 51},
     ##{'provincial_capital': '周口', 'url': 'zhoukou', 'page': 30},
     ## {'provincial_capital': '商丘', 'url': 'shangqiu', 'page': 39},
      #{'provincial_capital': '济源', 'url': 'jiyuan', 'page': 22},
      #{'provincial_capital': '漯河', 'url': 'luohe', 'page': 19},
      ##{'provincial_capital': '濮阳', 'url': 'puyang', 'page': 27},
     ## {'provincial_capital': '驻马店', 'url': 'zhumadian', 'page': 40},
     # {'provincial_capital': '鹤壁', 'url': 'hebi', 'page': 13},
     # # 湖北省
     ## {'provincial_capital': '武汉', 'url': 'wuhan', 'page': 48},
     ## {'provincial_capital': '襄樊', 'url': 'xiangfan', 'page': 28},
      #{'provincial_capital': '鄂州', 'url': 'ezhou', 'page': 19},
     #{'provincial_capital': '黄石', 'url': 'huangshi', 'page': 22},
     ##{'provincial_capital': '荆州', 'url': 'jingzhou', 'page': 36},
     ## {'provincial_capital': '宜昌', 'url': 'yichang', 'page': 71},
     ## {'provincial_capital': '荆门', 'url': 'jingmen', 'page': 33},
      #{'provincial_capital': '仙桃', 'url': 'xiantao', 'page': 15},
      # {'provincial_capital': '咸宁', 'url': 'xianning', 'page': 26},
     # {'provincial_capital': '天门', 'url': 'tianmen', 'page': 19},
     ## {'provincial_capital': '孝感', 'url': 'xiaogan', 'page': 33},
     #{'provincial_capital': '潜江', 'url': 'qianjiang', 'page': 13},
     ## {'provincial_capital': '黄冈', 'url': 'huanggang', 'page': 58},
      # {'provincial_capital': '神农架', 'url': 'shennongjia', 'page': 10},
     # {'provincial_capital': '恩施', 'url': 'enshi', 'page': 49},
     # # 湖南省
     # {'provincial_capital': '岳阳', 'url': 'yueyang', 'page': 49},
    # {'provincial_capital': '长沙', 'url': 'changsha', 'page': 66},
      #{'provincial_capital': '湘潭', 'url': 'xiangtan', 'page': 34},
      #{'provincial_capital': '株洲', 'url': 'zhuzhou', 'page': 72},
      # {'provincial_capital': '衡阳', 'url': 'hengyang', 'page': 48},
     # {'provincial_capital': '常德', 'url': 'changde', 'page': 48},
     # {'provincial_capital': '张家界', 'url': 'zhangjiajie', 'page': 22},
     #{'provincial_capital': '娄底', 'url': 'loudi', 'page': 35},
      # {'provincial_capital': '怀化', 'url': 'huaihua', 'page': 75},
     # {'provincial_capital': '永州', 'url': 'yongzhou', 'page': 74},
    ## {'provincial_capital': '益阳', 'url': 'yiyang', 'page': 33},
     # {'provincial_capital': '邵阳', 'url': 'shaoyang', 'page': 37},
     #  {'provincial_capital': '郴州', 'url': 'chenzhou', 'page': 43},
     # {'provincial_capital': '湘西', 'url': 'xiangxi', 'page': 16},
     # #黑龙江
     # {'provincial_capital': '哈尔滨', 'url': 'haerbin', 'page': 41},
     # {'provincial_capital': '齐齐哈尔', 'url': 'qiqihaer', 'page': 28},
     # {'provincial_capital': '牡丹江', 'url': 'mudanjiang', 'page': 18},
     # {'provincial_capital': '大庆', 'url': 'daqing', 'page': 15},
     # {'provincial_capital': '佳木斯', 'url': 'jiamusi', 'page': 19},
     # {'provincial_capital': '七台河', 'url': 'qitaihe', 'page': 5},
     # {'provincial_capital': '伊春', 'url': 'yichun', 'page': 8},
     # {'provincial_capital': '双鸭山', 'url': 'shuangyashan', 'page': 10},
     # {'provincial_capital': '大兴安岭', 'url': 'daxinganling', 'page': 4},
     ##{'provincial_capital': '绥化', 'url': 'suihua', 'page': 32},
     # {'provincial_capital': '鸡西', 'url': 'jixi', 'page': 13},
     # {'provincial_capital': '鹤岗', 'url': 'hegang', 'page': 10},
     # {'provincial_capital': '黑河', 'url': 'heihe', 'page': 15},
     # # 海南省
     # {'provincial_capital': '海口', 'url': 'haikou', 'page': 16},
     # {'provincial_capital': '三亚', 'url': 'sanya', 'page': 12},
     # {'provincial_capital': '白沙', 'url': 'baishaxian', 'page': 8},
     # {'provincial_capital': '保亭', 'url': 'baotingxian', 'page': 9},
     # {'provincial_capital': '昌江', 'url': 'changjiangxian', 'page': 5},
     # {'provincial_capital': '澄迈', 'url': 'chengmaixian', 'page': 10},
     # {'provincial_capital': '定安', 'url': 'dinganxian', 'page': 10},
     # #{'provincial_capital': '东方', 'url': 'dongfang', 'page': 6},
     # #{'provincial_capital': '乐东', 'url': 'ledong', 'page': 12},
     # {'provincial_capital': '临高县', 'url': 'lingaoxian', 'page': 15},
     # {'provincial_capital': '陵水', 'url': 'lingshui', 'page': 9},
     # {'provincial_capital': '琼海', 'url': 'qionghai', 'page': 15},
     # {'provincial_capital': '琼中', 'url': 'qiongzhong', 'page': 12},
     # {'provincial_capital': '屯昌县', 'url': 'tunchangxian', 'page': 9},
     # {'provincial_capital': '万宁', 'url': 'wanning', 'page': 10},
     # {'provincial_capital': '文昌', 'url': 'wenchang', 'page': 15},
     # {'provincial_capital': '五指山', 'url': 'wuzhishan', 'page': 6},
     # {'provincial_capital': '儋州', 'url': 'danzhou', 'page': 17},
     # {'provincial_capital': '三沙', 'url': 'sansha', 'page': 1},
     # # 吉林省
     ##{'provincial_capital': '长春', 'url': 'changchun', 'page': 37},
     # {'provincial_capital': '吉林', 'url': 'jilin', 'page': 24},
     # {'provincial_capital': '四平', 'url': 'siping', 'page': 22},
     # {'provincial_capital': '延边', 'url': 'yanbian', 'page': 9},
     # {'provincial_capital': '松原', 'url': 'songyuan', 'page': 12},
     # {'provincial_capital': '白城', 'url': 'baicheng', 'page': 18},
     # {'provincial_capital': '白山', 'url': 'baishan', 'page': 12},
     # {'provincial_capital': '辽源', 'url': 'liaoyuan', 'page': 18},
     # {'provincial_capital': '通化', 'url': 'tonghua', 'page': 15},
     # # 江苏省
     # {'provincial_capital': '无锡', 'url': 'wuxi', 'page': 43},
     # {'provincial_capital': '镇江', 'url': 'zhenjiang', 'page': 17},
     # {'provincial_capital': '苏州', 'url': 'suzhou', 'page': 68},
     # {'provincial_capital': '南通', 'url': 'nantong', 'page': 58},
     ##{'provincial_capital': '扬州', 'url': 'yangzhou', 'page': 44},
     # #{'provincial_capital': '徐州', 'url': 'xuzhou', 'page': 34},
     # #{'provincial_capital': '连云港', 'url': 'lianyungang', 'page': 31},
     #{'provincial_capital': '常州', 'url': 'changzhou', 'page': 40},
     # {'provincial_capital': '泰州', 'url': 'taizhou', 'page': 19},
     # {'provincial_capital': '宿迁', 'url': 'suqian', 'page': 31},
     # {'provincial_capital': '淮安', 'url': 'huaian', 'page': 35},
     # # 江西省
     # {'provincial_capital': '南昌', 'url': 'nanchang', 'page': 48},
     # {'provincial_capital': '九江', 'url': 'jiujiang', 'page': 37},
     {'provincial_capital': '景德镇', 'url': 'jingdezhen', 'page': 13},
     # {'provincial_capital': '吉安', 'url': 'jian', 'page': 39},
     # {'provincial_capital': '宜春', 'url': 'yiichun', 'page': 44},
     # {'provincial_capital': '抚州', 'url': 'fuuzhou', 'page': 36},
     # {'provincial_capital': '新余', 'url': 'xinyu', 'page': 18},
     # {'provincial_capital': '萍乡', 'url': 'pingxiang', 'page': 24},
     # {'provincial_capital': '赣州', 'url': 'ganzhou', 'page': 74},
     # {'provincial_capital': '鹰潭', 'url': 'yingtan', 'page': 18},
     # {'provincial_capital': '上饶', 'url': 'shangrao', 'page': 38},
     # # 辽宁省
     # {'provincial_capital': '沈阳', 'url': 'shenyang', 'page': 28},
     # {'provincial_capital': '大连', 'url': 'dalian', 'page': 46},
     # {'provincial_capital': '鞍山', 'url': 'anshan', 'page': 28},
     # {'provincial_capital': '抚顺', 'url': 'fushun', 'page': 19},
     # {'provincial_capital': '本溪', 'url': 'benxi', 'page': 20},
     # {'provincial_capital': '丹东', 'url': 'dandong', 'page': 41},
     # {'provincial_capital': '锦州', 'url': 'jinzhou', 'page': 33},
     # {'provincial_capital': '营口', 'url': 'yingkou', 'page': 14},
     # {'provincial_capital': '辽阳', 'url': 'liaoyang', 'page': 13},
     # {'provincial_capital': '盘锦', 'url': 'panjin', 'page': 13},
     # {'provincial_capital': '葫芦岛', 'url': 'huludao', 'page': 26},
     # {'provincial_capital': '朝阳', 'url': 'chaoyang', 'page': 33},
     # {'provincial_capital': '铁岭', 'url': 'tieling', 'page': 29},
     # {'provincial_capital': '阜新', 'url': 'fuxin', 'page': 17},
     # # 内蒙古
     # {'provincial_capital': '呼和浩特', 'url': 'huhehaote', 'page': 27},
     # {'provincial_capital': '包头', 'url': 'baotou', 'page': 18},
     # {'provincial_capital': '乌兰察布', 'url': 'wulanchabu', 'page': 29},
     # {'provincial_capital': '乌海', 'url': 'wuhai', 'page': 4},
     # {'provincial_capital': '兴安盟', 'url': 'xinganmeng', 'page': 15},
     # {'provincial_capital': '呼伦贝尔', 'url': 'hulunbeier', 'page': 15},
     # {'provincial_capital': '赤峰', 'url': 'chifeng', 'page': 33},
     # {'provincial_capital': '通辽', 'url': 'tongliao', 'page': 25},
     # {'provincial_capital': '鄂尔多斯', 'url': 'eerduosi', 'page': 34},
     # {'provincial_capital': '阿拉善盟', 'url': 'alashan', 'page': 15},
     # {'provincial_capital': '巴彦淖尔盟', 'url': 'bayannaoer', 'page': 12},
     # {'provincial_capital': '锡林郭勒盟', 'url': 'xilinguole', 'page': 16},
     # # 宁夏省
     # {'provincial_capital': '银川', 'url': 'yinchuan', 'page': 13},
     # {'provincial_capital': '中卫', 'url': 'zhongwei', 'page': 12},
     # {'provincial_capital': '吴忠', 'url': 'wuzhong', 'page': 15},
     # {'provincial_capital': '石嘴山', 'url': 'shizuishan', 'page': 13},
     # {'provincial_capital': '固原', 'url': 'guyuan', 'page': 19},
     # # 青海省
     # {'provincial_capital': '西宁', 'url': 'xining', 'page': 12},
     # {'provincial_capital': '海东地区', 'url': 'haidong', 'page': 6},
     # {'provincial_capital': '海北州', 'url': 'haibei', 'page': 11},
     # {'provincial_capital': '海南州', 'url': 'hainan', 'page': 12},
     # {'provincial_capital': '果洛州', 'url': 'guoluo', 'page': 8},
     # {'provincial_capital': '黄南州', 'url': 'huangnan', 'page': 8},
     # {'provincial_capital': '玉树州', 'url': 'yushu', 'page': 10},
     # {'provincial_capital': '海西州', 'url': 'haixi', 'page': 9},
     # # 山西省
     # {'provincial_capital': '太原', 'url': 'taiyuan', 'page': 20},
     # {'provincial_capital': '临汾', 'url': 'linfen', 'page': 33},
     # {'provincial_capital': '吕梁', 'url': 'lvliang', 'page': 34},
     # {'provincial_capital': '大同', 'url': 'datong', 'page': 16},
     # {'provincial_capital': '忻州', 'url': 'xinzhou', 'page': 23},
     # {'provincial_capital': '晋中', 'url': 'jinzhong', 'page': 31},
     # {'provincial_capital': '晋城', 'url': 'jincheng', 'page': 32},
     # {'provincial_capital': '朔州', 'url': 'shuozhou', 'page': 13},
     # {'provincial_capital': '运城', 'url': 'yuncheng', 'page': 31},
     # {'provincial_capital': '长治', 'url': 'changzhi', 'page': 42},
     # {'provincial_capital': '阳泉', 'url': 'yangquan', 'page': 14},
     # # 山东省
     # {'provincial_capital': '济南', 'url': 'jinan', 'page': 58},
     # {'provincial_capital': '青岛', 'url': 'qingdao', 'page': 38},
     # {'provincial_capital': '淄博', 'url': 'zibo', 'page': 23},
     # {'provincial_capital': '德州', 'url': 'dezhou', 'page': 34},
     # {'provincial_capital': '烟台', 'url': 'yantai', 'page': 31},
     # {'provincial_capital': '潍坊', 'url': 'weifang', 'page': 43},
     # {'provincial_capital': '泰安', 'url': 'taian', 'page': 33},
     # {'provincial_capital': '东营', 'url': 'dongying', 'page': 20},
     # {'provincial_capital': '威海', 'url': 'weihai', 'page': 17},
     # {'provincial_capital': '临沂', 'url': 'linyi', 'page': 43},
     # {'provincial_capital': '日照', 'url': 'rizhao', 'page': 23},
     # {'provincial_capital': '枣庄', 'url': 'zaozhuang', 'page': 22},
     # {'provincial_capital': '济宁', 'url': 'jining', 'page': 35},
     # {'provincial_capital': '滨州', 'url': 'binzhou', 'page': 32},
     # {'provincial_capital': '聊城', 'url': 'liaocheng', 'page': 35},
     # {'provincial_capital': '莱芜', 'url': 'laiwu', 'page': 1},
     # {'provincial_capital': '菏泽', 'url': 'heze', 'page': 43},
     # # 陕西省
     # {'provincial_capital': '西安', 'url': 'xian', 'page': 52},
     # {'provincial_capital': '咸阳', 'url': 'xianyang', 'page': 25},
     # {'provincial_capital': '延安', 'url': 'yanan', 'page': 31},
     # {'provincial_capital': '宝鸡', 'url': 'baoji', 'page': 44},
     # {'provincial_capital': '商洛', 'url': 'shangluo', 'page': 29},
     # {'provincial_capital': '安康', 'url': 'ankang', 'page': 47},
     # {'provincial_capital': '榆林', 'url': 'yuulin', 'page': 53},
     # {'provincial_capital': '渭南', 'url': 'weinan', 'page': 34},
     # {'provincial_capital': '铜川', 'url': 'tongchuan', 'page': 17},
     # # 四川省
     # {'provincial_capital': '成都', 'url': 'chengdu', 'page': 80},
     # {'provincial_capital': '自贡', 'url': 'zigong', 'page': 22},
     # {'provincial_capital': '绵阳', 'url': 'mianyang', 'page': 54},
     # {'provincial_capital': '泸州', 'url': 'luzhou', 'page': 57},
     # {'provincial_capital': '宜宾', 'url': 'yibin', 'page': 49},
     # {'provincial_capital': '内江', 'url': 'neijiang', 'page': 23},
     # {'provincial_capital': '资阳', 'url': 'ziyang', 'page': 27},
     # {'provincial_capital': '乐山', 'url': 'leshan', 'page': 40},
     # {'provincial_capital': '眉山', 'url': 'meishan', 'page': 15},
     # {'provincial_capital': '凉山', 'url': 'liangshan', 'page': 48},
     # {'provincial_capital': '南充', 'url': 'nanchong', 'page': 41},
     # {'provincial_capital': '巴中', 'url': 'bazhong', 'page': 51},
     # {'provincial_capital': '广元', 'url': 'guangyuan', 'page': 60},
     # {'provincial_capital': '广安', 'url': 'guangan', 'page': 24},
     # {'provincial_capital': '德阳', 'url': 'deyang', 'page': 33},
     # {'provincial_capital': '甘孜', 'url': 'ganzi', 'page': 26},
     # {'provincial_capital': '达州', 'url': 'dazhou', 'page': 48},
     # {'provincial_capital': '遂宁', 'url': 'suining', 'page': 23},
     # {'provincial_capital': '阿坝', 'url': 'aba', 'page': 23},
     # {'provincial_capital': '雅安', 'url': 'yaan', 'page': 21},
     # # 新疆维吾尔自治区
     # {'provincial_capital': '乌鲁木齐', 'url': 'wulumuqi', 'page': 14},
     # {'provincial_capital': '伊犁州', 'url': 'yili', 'page': 16},
     # {'provincial_capital': '克拉玛依', 'url': 'kelamayi', 'page': 2},
     # {'provincial_capital': '博尔塔拉', 'url': 'boertala', 'page': 8},
     # {'provincial_capital': '吐鲁番', 'url': 'tulufan', 'page': 5},
     # {'provincial_capital': '塔城', 'url': 'tacheng', 'page': 16},
     # {'provincial_capital': '昌吉', 'url': 'changji', 'page': 14},
     # {'provincial_capital': '石河子', 'url': 'shihezi', 'page': 3},
     # {'provincial_capital': '阿克苏', 'url': 'akesu', 'page': 22},
     # {'provincial_capital': '阿勒泰', 'url': 'aletai', 'page': 19},
     # {'provincial_capital': '巴音郭楞', 'url': 'bayinguoleng', 'page': 17},
     # {'provincial_capital': '哈密地区', 'url': 'hami', 'page': 10},
     # {'provincial_capital': '和田地区', 'url': 'hetian', 'page': 17},
     # {'provincial_capital': '喀什地区', 'url': 'kashi', 'page': 32},
     # {'provincial_capital': '克孜勒苏', 'url': 'kezilesu', 'page': 14},
     # {'provincial_capital': '北屯', 'url': 'beitun', 'page': 1},
     # {'provincial_capital': '铁门关', 'url': 'tiemenguan', 'page': 1},
     # {'provincial_capital': '双河', 'url': 'shuanghe', 'page': 2},
     # {'provincial_capital': '可克达拉', 'url': 'kekedala', 'page': 2},
     # {'provincial_capital': '昆玉', 'url': 'kunyu', 'page': 2},
     # {'provincial_capital': '五家渠', 'url': 'wujiaju', 'page': 2},
     # {'provincial_capital': '阿拉尔', 'url': 'alaer', 'page': 1},
     # {'provincial_capital': '图木舒克', 'url': 'tumushuke', 'page': 1},
     # # 香港
     # {'provincial_capital': '香港', 'url': 'xianggang', 'page': 17},
     # # 西藏自治区
     # {'provincial_capital': '拉萨', 'url': 'lasa', 'page': 17},
     # {'provincial_capital': '山南地区', 'url': 'shannan', 'page': 15},
     # {'provincial_capital': '日喀则', 'url': 'rikaze', 'page': 22},
     # {'provincial_capital': '阿里地区', 'url': 'ali', 'page': 11},
     # {'provincial_capital': '昌都地区', 'url': 'changdu', 'page': 21},
     # {'provincial_capital': '林芝地区', 'url': 'linzhi', 'page': 13},
     # {'provincial_capital': '那曲地区', 'url': 'naqu', 'page': 15},
     # # 云南省
     # {'provincial_capital': '昆明', 'url': 'kunming', 'page': 40},
     # {'provincial_capital': '玉溪', 'url': 'yuxi', 'page': 22},
     # {'provincial_capital': '大理', 'url': 'dali', 'page': 35},
     # {'provincial_capital': '曲靖', 'url': 'qujing', 'page': 44},
     # {'provincial_capital': '楚雄', 'url': 'chuxiong', 'page': 34},
     # {'provincial_capital': '红河', 'url': 'honghe', 'page': 28},
     # {'provincial_capital': '西双版纳', 'url': 'xishuangbanna', 'page': 13},
     # {'provincial_capital': '保山', 'url': 'baoshan', 'page': 26},
     # {'provincial_capital': '德宏州', 'url': 'dehong', 'page': 16},
     # {'provincial_capital': '迪庆州', 'url': 'diqing', 'page': 12},
     # {'provincial_capital': '丽江', 'url': 'lijiang', 'page': 18},
     # {'provincial_capital': '临沧地区', 'url': 'lincang', 'page': 13},
     # {'provincial_capital': '怒江州', 'url': 'nujiang', 'page': 14},
     # {'provincial_capital': '普洱', 'url': 'puer', 'page': 28},
     # # 浙江省
     # {'provincial_capital': '杭州', 'url': 'hangzhou', 'page': 75},
     # {'provincial_capital': '嘉兴', 'url': 'jiaxing', 'page': 78},
     # {'provincial_capital': '绍兴', 'url': 'shaoxing', 'page': 38},
     # {'provincial_capital': '湖州', 'url': 'huzhou', 'page': 33},
     # {'provincial_capital': '宁波', 'url': 'ningbo', 'page': 70},
     # {'provincial_capital': '台州', 'url': 'taiizhou', 'page': 32},
     # {'provincial_capital': '温州', 'url': 'wenzhou', 'page': 45},
     # {'provincial_capital': '金华', 'url': 'jinhua', 'page': 38},
     # {'provincial_capital': '舟山', 'url': 'zhoushan', 'page': 31},
     # {'provincial_capital': '丽水', 'url': 'lishui', 'page': 38},
     # {'provincial_capital': '衢州', 'url': 'quzhou', 'page': 37}
    ]
    return cates

print(len(index()))

